module.exports = [
  "Hamlet",
  "Romeo and Juliet",
  "Macbeth",
  "A Midsummer Night's Dream",
  "Othello",
  "King Lear",
  "Much Ado About Nothing",
  "Twelfth Night",
  "The Tempest",
  "The Merchant of Venice",
  "Julius Caesar",
  "The Taming of the Shrew",
  "As You Like It",
  "Shakespeare's Sonnets",
  "Antony and Cleopatra",
  "Richard III",
  "Henry V",
  "The Winter's Tale",
  "Titus Andronicus",
  "The Comedy of Errors",
  "King Henry IV, Part 1 (Wars of the Roses, #2)",
  "Richard II",
  "Measure for Measure",
  "Love's Labour's Lost",
  "The Two Gentlemen of Verona",
  "Coriolanus",
  "Troilus and Cressida",
  "King Henry VI, Part 2",
  "Cymbeline",
  "Pericles",
  "The Merry Wives of Windsor",
  "Henry VIII",
  "King Henry VI, Part 3",
  "King John",
  "Ages of Man: Readings from Shakespeare",
  "Henry IV, Part 2 (Wars of the Roses, #3)",
  "Henry VI, Part 1",
  "Timon of Athens",
  "All's Well That Ends Well",
  "The Complete Works",
  "The Phoenix and the Turtle",
  "King Edward III",
  "Sonnets to a Young Man",
  "The Two Noble Kinsmen",
  "Venus and Adonis",
  "A Lover's Complaint",
  "The Rape of Lucrece",
  "The London Prodigal",
  "Henry VI, Part 3",
  "Funeral Elegy",
  "To the Queen",
  "Pride and Prejudice",
  "Jane Eyre",
  "The Lord of the Rings (The Lord of the Rings, #1-3)",
  "Wuthering Heights",
  "1984",
  "Harry Potter Boxset (Harry Potter, #1-7)",
  "The Picture of Dorian Gray",
  "The Complete Works",
  "The Chronicles of Narnia (Chronicles of Narnia, #1-7)",
  "Emma",
  "Sense and Sensibility",
  "Persuasion",
  "Animal Farm",
  "Frankenstein",
  "Alice's Adventures in Wonderland & Through the Looking-Glass",
  "Lord of the Flies",
  "Great Expectations",
  "Rebecca",
  "The Importance of Being Earnest",
  "The Hobbit",
  "Dracula",
  "A Christmas Carol",
  "A Tale of Two Cities",
  "Brave New World",
  "The Golden Compass (His Dark Materials, #1)",
  "The Canterbury Tales",
  "Atonement",
  "The Adventures of Sherlock Holmes (Sherlock Holmes, #3)",
  "The Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy, #1)",
  "Harry Potter and the Sorcerer's Stone (Harry Potter, #1)",
  "Never Let Me Go",
  "The Secret Garden",
  "Hamlet",
  "Middlemarch",
  "Mrs. Dalloway",
  "Mansfield Park",
  "The Strange Case of Dr. Jekyll and Mr. Hyde",
  "Oliver Twist",
  "Gulliver's Travels",
  "Robinson Crusoe",
  "Romeo and Juliet",
  "And Then There Were None",
  "Winnie-the-Pooh (Winnie-the-Pooh, #1)",
  "Watership Down",
  "Brideshead Revisited",
  "Heart of Darkness",
  "Far from the Madding Crowd",
  "Tess of the D'Urbervilles",
  "The Remains of the Day",
  "To the Lighthouse",
  "Beowulf",
  "Paradise Lost",
  "Bleak House",
  "A Clockwork Orange",
  "Possession",
  "Northanger Abbey",
  "Macbeth",
  "A Room with a View",
  "Harry Potter and the Goblet of Fire (Harry Potter, #4)",
  "Harry Potter and the Prisoner of Azkaban (Harry Potter, #3)",
  "The Waste Land and Other Writings",
  "Vanity Fair",
  "A Study in Scarlet (Sherlock Holmes, #1)",
  "Harry Potter and the Half-Blood Prince (Harry Potter, #6)",
  "I Capture the Castle",
  "Three Men in a Boat (Three Men, #1)",
  "Murder on the Orient Express (Hercule Poirot, #10)",
  "David Copperfield",
  "Jonathan Strange & Mr Norrell",
  "Charlie and the Chocolate Factory (Charlie Bucket, #1)",
  "Harry Potter and the Deathly Hallows (Harry Potter, #7)",
  "Le Morte d'Arthur: King Arthur and the Legends of the Round Table",
  "The Once and Future King (The Once and Future King #1-4)",
  "Harry Potter and the Chamber of Secrets (Harry Potter, #2)",
  "The Amber Spyglass (His Dark Materials, #3)",
  "A Passage to India",
  "The Woman in White",
  "The Subtle Knife (His Dark Materials, #2)",
  "Alice in Wonderland (Alice's Adventures in Wonderland, #1)",
  "Wives and Daughters",
  "Rosencrantz and Guildenstern Are Dead",
  "The Tenant of Wildfell Hall",
  "Treasure Island",
  "North and South",
  "Pygmalion",
  "Of Human Bondage",
  "Utopia",
  "The End of the Affair",
  "The Forsyte Saga (The Forsyte Chronicles, #1-3)",
  "Watchmen",
  "King Lear",
  "The History of Tom Jones, a Foundling",
  "A Little Princess",
  "The Magus",
  "The Prime of Miss Jean Brodie",
  "The Code of the Woosters (Jeeves, #7)",
  "Howl's Moving Castle (Howl's Moving Castle, #1)",
  "Sir Gawain and the Green Knight",
  "Cloud Atlas",
  "The Pickwick Papers",
  "To Kill a Mockingbird",
  "1984",
  "The Lord of the Rings (The Lord of the Rings, #1-3)",
  "The Great Gatsby",
  "Harry Potter and the Sorcerer's Stone (Harry Potter, #1)",
  "Animal Farm",
  "The Diary of a Young Girl",
  "The Hobbit",
  "The Little Prince",
  "The Catcher in the Rye",
  "Fahrenheit 451",
  "The Grapes of Wrath",
  "The Lion, the Witch, and the Wardrobe (Chronicles of Narnia, #1)",
  "One Hundred Years of Solitude",
  "Brave New World",
  "The Catcher in the Rye",
  "Gone with the Wind",
  "Of Mice and Men",
  "Il signore delle mosche",
  "The Giver (The Giver, #1)",
  "Harry Potter and the Prisoner of Azkaban (Harry Potter, #3)",
  "Slaughterhouse-Five",
  "Lolita",
  "East of Eden",
  "One Flew Over the Cuckoo's Nest",
  "The Ultimate Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy #1-5)",
  "Memoirs of a Geisha",
  "The Stranger",
  "The Handmaid's Tale",
  "The Fellowship of the Ring (The Lord of the Rings, #1)",
  "Charlotte's Web",
  "A Wrinkle in Time (A Wrinkle in Time Quintet, #1)",
  "The Chronicles of Narnia (Chronicles of Narnia, #1-7)",
  "Harry Potter and the Chamber of Secrets (Harry Potter, #2)",
  "The Old Man and the Sea",
  "Ender's Game (The Ender Quintet, #1)",
  "The Giving Tree",
  "A Tree Grows in Brooklyn",
  "The Return of the King (The Lord of the Rings, #3)",
  "The Two Towers (The Lord of the Rings, #2)",
  "Night (The Night Trilogy, #1)",
  "Watership Down",
  "The Bell Jar",
  "In Cold Blood",
  "Atlas Shrugged",
  "Green Eggs and Ham",
  "The Alchemist",
  "The Poisonwood Bible",
  "Love in the Time of Cholera",
  "Anne of Green Gables (Anne of Green Gables, #1)",
  "The Color Purple",
  "A Prayer for Owen Meany",
  "The Complete Sherlock Holmes",
  "The Stand",
  "The Unbearable Lightness of Being",
  "Where the Wild Things Are",
  "The Lorax",
  "Siddhartha",
  "The Metamorphosis",
  "The Name of the Rose",
  "Charlie and the Chocolate Factory (Charlie Bucket, #1)",
  "The Secret Garden",
  "Rebecca",
  "On the Road",
  "The Pillars of the Earth  (The Pillars of the Earth, #1)",
  "The Sun Also Rises",
  "Ulysses",
  "Dune (Dune Chronicles, #1)",
  "The Master and Margarita",
  "The Good Earth (House of Earth, #1)",
  "The Outsiders",
  "Beloved",
  "The Hitchhiker's Guide to the Galaxy (Hitchhiker's Guide to the Galaxy, #1)",
  "All Quiet on the Western Front",
  "A Confederacy of Dunces",
  "The Fountainhead",
  "The Joy Luck Club",
  "The Sound and the Fury",
  "Angela's Ashes (Frank McCourt, #1)",
  "For Whom the Bell Tolls",
  "The World According to Garp",
  "A Farewell to Arms",
  "Little House on the Prairie (Little House, #2)",
  "Invisible Man",
  "Their Eyes Were Watching God",
  "A Clockwork Orange",
  "Where the Red Fern Grows",
  "Mere Christianity",
  "Waiting for Godot",
  "The Red Tent",
  "Sophie's Choice",
  "Lonesome Dove",
  "Fear and Loathing in Las Vegas",
  "The Things They Carried",
  "Franny and Zooey",
  "Flowers for Algernon",
  "A Portrait of the Artist as a Young Man",
  "Blindness",
  "To the Lighthouse",
  "Cat's Cradle"
]