module.exports = [
  "Hamlet",
  "Romeo and Juliet",
  "Macbeth",
  "A Midsummer Night's Dream",
  "Othello",
  "King Lear",
  "Much Ado About Nothing",
  "Twelfth Night",
  "The Tempest",
  "The Merchant of Venice",
  "Julius Caesar",
  "The Taming of the Shrew",
  "As You Like It",
  "Shakespeare's Sonnets",
  "Antony and Cleopatra",
  "Richard III",
  "Henry V",
  "The Winter's Tale",
  "Titus Andronicus",
  "The Comedy of Errors",
  "King Henry IV, Part 1",
  "Richard II",
  "Measure for Measure",
  "Love's Labour's Lost",
  "The Two Gentlemen of Verona",
  "Coriolanus",
  "Troilus and Cressida",
  "King Henry VI, Part 2",
  "Cymbeline",
  "Pericles",
  "The Merry Wives of Windsor",
  "Henry VIII",
  "King Henry VI, Part 3",
  "King John",
  "Ages of Man: Readings from Shakespeare",
  "Henry IV, Part 2",
  "Henry VI, Part 1",
  "Timon of Athens",
  "All's Well That Ends Well",
  "The Complete Works",
  "The Phoenix and the Turtle",
  "King Edward III",
  "Sonnets to a Young Man",
  "The Two Noble Kinsmen",
  "Venus and Adonis",
  "A Lover's Complaint",
  "The Rape of Lucrece",
  "The London Prodigal",
  "Henry VI, Part 3",
  "Funeral Elegy",
  "To the Queen",
  "Pride and Prejudice",
  "Jane Eyre",
  "The Lord of the Rings",
  "Wuthering Heights",
  "1984",
  "Harry Potter Boxset",
  "The Picture of Dorian Gray",
  "The Complete Works",
  "The Chronicles of Narnia",
  "Emma",
  "Sense and Sensibility",
  "Persuasion",
  "Animal Farm",
  "Frankenstein",
  "Alice's Adventures in Wonderland & Through the Looking-Glass",
  "Lord of the Flies",
  "Great Expectations",
  "Rebecca",
  "The Importance of Being Earnest",
  "The Hobbit",
  "Dracula",
  "A Christmas Carol",
  "A Tale of Two Cities",
  "Brave New World",
  "The Golden Compass",
  "The Canterbury Tales",
  "Atonement",
  "The Adventures of Sherlock Holmes",
  "The Hitchhiker's Guide to the Galaxy",
  "Harry Potter and the Sorcerer's Stone",
  "Never Let Me Go",
  "The Secret Garden",
  "Hamlet",
  "Middlemarch",
  "Mrs. Dalloway",
  "Mansfield Park",
  "The Strange Case of Dr. Jekyll and Mr. Hyde",
  "Oliver Twist",
  "Gulliver's Travels",
  "Robinson Crusoe",
  "Romeo and Juliet",
  "And Then There Were None",
  "Winnie-the-Pooh",
  "Watership Down",
  "Brideshead Revisited",
  "Heart of Darkness",
  "Far from the Madding Crowd",
  "Tess of the D'Urbervilles",
  "The Remains of the Day",
  "To the Lighthouse",
  "Beowulf",
  "Paradise Lost",
  "Bleak House",
  "A Clockwork Orange",
  "Possession",
  "Northanger Abbey",
  "Macbeth",
  "A Room with a View",
  "Harry Potter and the Goblet of Fire",
  "Harry Potter and the Prisoner of Azkaban",
  "The Waste Land and Other Writings",
  "Vanity Fair",
  "A Study in Scarlet",
  "Harry Potter and the Half-Blood Prince",
  "I Capture the Castle",
  "Three Men in a Boat",
  "Murder on the Orient Express",
  "David Copperfield",
  "Jonathan Strange & Mr Norrell",
  "Charlie and the Chocolate Factory",
  "Harry Potter and the Deathly Hallows",
  "Le Morte d'Arthur: King Arthur and the Legends of the Round Table",
  "The Once and Future King",
  "Harry Potter and the Chamber of Secrets",
  "The Amber Spyglass",
  "A Passage to India",
  "The Woman in White",
  "The Subtle Knife",
  "Alice in Wonderland",
  "Wives and Daughters",
  "Rosencrantz and Guildenstern Are Dead",
  "The Tenant of Wildfell Hall",
  "Treasure Island",
  "North and South",
  "Pygmalion",
  "Of Human Bondage",
  "Utopia",
  "The End of the Affair",
  "The Forsyte Saga",
  "Watchmen",
  "King Lear",
  "The History of Tom Jones, a Foundling",
  "A Little Princess",
  "The Magus",
  "The Prime of Miss Jean Brodie",
  "The Code of the Woosters",
  "Howl's Moving Castle",
  "Sir Gawain and the Green Knight",
  "Cloud Atlas",
  "The Pickwick Papers",
  "To Kill a Mockingbird",
  "1984",
  "The Lord of the Rings",
  "The Great Gatsby",
  "Harry Potter and the Sorcerer's Stone",
  "Animal Farm",
  "The Diary of a Young Girl",
  "The Hobbit",
  "The Little Prince",
  "The Catcher in the Rye",
  "Fahrenheit 451",
  "The Grapes of Wrath",
  "The Lion, the Witch, and the Wardrobe",
  "One Hundred Years of Solitude",
  "Brave New World",
  "The Catcher in the Rye",
  "Gone with the Wind",
  "Of Mice and Men",
  "Il signore delle mosche",
  "The Giver",
  "Harry Potter and the Prisoner of Azkaban",
  "Slaughterhouse-Five",
  "Lolita",
  "East of Eden",
  "One Flew Over the Cuckoo's Nest",
  "The Ultimate Hitchhiker's Guide to the Galaxy",
  "Memoirs of a Geisha",
  "The Stranger",
  "The Handmaid's Tale",
  "The Fellowship of the Ring",
  "Charlotte's Web",
  "A Wrinkle in Time",
  "The Chronicles of Narnia",
  "Harry Potter and the Chamber of Secrets",
  "The Old Man and the Sea",
  "Ender's Game",
  "The Giving Tree",
  "A Tree Grows in Brooklyn",
  "The Return of the King",
  "The Two Towers",
  "Night",
  "Watership Down",
  "The Bell Jar",
  "In Cold Blood",
  "Atlas Shrugged",
  "Green Eggs and Ham",
  "The Alchemist",
  "The Poisonwood Bible",
  "Love in the Time of Cholera",
  "Anne of Green Gables",
  "The Color Purple",
  "A Prayer for Owen Meany",
  "The Complete Sherlock Holmes",
  "The Stand",
  "The Unbearable Lightness of Being",
  "Where the Wild Things Are",
  "The Lorax",
  "Siddhartha",
  "The Metamorphosis",
  "The Name of the Rose",
  "Charlie and the Chocolate Factory",
  "The Secret Garden",
  "Rebecca",
  "On the Road",
  "The Pillars of the Earth ",
  "The Sun Also Rises",
  "Ulysses",
  "Dune",
  "The Master and Margarita",
  "The Good Earth",
  "The Outsiders",
  "Beloved",
  "The Hitchhiker's Guide to the Galaxy",
  "All Quiet on the Western Front",
  "A Confederacy of Dunces",
  "The Fountainhead",
  "The Joy Luck Club",
  "The Sound and the Fury",
  "Angela's Ashes",
  "For Whom the Bell Tolls",
  "The World According to Garp",
  "A Farewell to Arms",
  "Little House on the Prairie",
  "Invisible Man",
  "Their Eyes Were Watching God",
  "A Clockwork Orange",
  "Where the Red Fern Grows",
  "Mere Christianity",
  "Waiting for Godot",
  "The Red Tent",
  "Sophie's Choice",
  "Lonesome Dove",
  "Fear and Loathing in Las Vegas",
  "The Things They Carried",
  "Franny and Zooey",
  "Flowers for Algernon",
  "A Portrait of the Artist as a Young Man",
  "Blindness",
  "To the Lighthouse",
  "Cat's Cradle"
]